version: "2"

linters-settings:
  gocyclo:
    min-complexity: 15
  staticcheck:
    checks: "all"
  goimports:
    local-prefixes: github.com/osteele/liquid
  goconst:
    min-len: 3
    min-occurrences: 3
  dupl:
    threshold: 150
  errcheck:
    check-type-assertions: true
    check-blank: false
  gosec:
    excludes: []
  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy for most projects
  misspell:
    locale: US

linters:
  enable:
    # Core quality linters (non-controversial)
    - govet
    - staticcheck
    - ineffassign
    - unused

    # Bug detection
    - errcheck
    - bodyclose
    - contextcheck
    - nilerr
    - copyloopvar # Detects loop variable issues

    # Code quality
    - gocyclo
    - dupl
    - unconvert
    - misspell

    # Security
    - gosec

    # Style (minimal, non-controversial)
    - whitespace

  # Explicitly disable overly strict linters
  disable:
    - gochecknoglobals # Too restrictive
    - err113 # Too strict for error handling (was goerr113)
    - wrapcheck # Too strict for error handling
    - exhaustruct # Too noisy
    - funlen # Function length is contextual
    - goconst # Too many false positives

run:
  timeout: 5m
  tests: true # Include test files
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-files:
    - "expressions/scanner.go"

issues:
  fix: true # Auto-fix what can be fixed
  max-same-issues: 3 # Show at most 3 issues of the same type
  max-issues-per-linter: 50

  # Exclude some linters from running on test files
  exclude-rules:
    - path: values/drop_test\.go
      linters: [staticcheck]
      text: "S1005:"

    # Exclude all linters for generated scanner file
    - path: expressions/scanner.go
      linters:
        - gocyclo
        - unconvert
        - unused
        - staticcheck
        - govet
        - ineffassign
        - errcheck
        - bodyclose
        - contextcheck
        - nilerr
        - copyloopvar
        - dupl
        - misspell
        - gosec
        - whitespace
        - godot


    # Exclude third party, builtin, examples
    - path: (third_party|builtin|examples|vendor)/
      linters:
        - all # Disable all linters for these directories

    # Common exclusions for tests
    - path: _test\.go
      linters:
        - gosec # Security issues less critical in tests
        - dupl # Test code often has similar patterns
        - errcheck # Error checking can be relaxed in tests
        - goconst # Test strings don't need to be constants

    # Generated code exclusions
    - path: \.pb\.go$
      linters:
        - all # Disable all linters for protobuf files
    - path: \.gen\.go$
      linters:
        - all # Disable all linters for generated files

    # Common false positives
    - text: "Error return value of .((Close|Write|Flush))` is not checked"
      linters: [errcheck]
      # Often intentionally ignored in deferred cleanup

output:
  formats:
    default: colored-line-number
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true # Remove duplicate issues on the same line
