version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupword
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: values/drop_test.go
        text: 'S1005:'
      - linters:
          - deadcode
          - funcorder
          - gocritic
          - revive
          - staticcheck
          - unconvert
          - unused
          - varcheck
        path: expressions/scanner.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - expressions/scanner.go

issues:
  fix: true