issues:
  exclude-rules:
    - linters: [gosimple]
      path: values/drop_test.go # see the note in the file
      text: "S1005:"

    # go generate introduces these
    - path: expressions/scanner.go
      linters: [deadcode, unused, varcheck, revive, stylecheck, gocritic, unconvert]
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - varnamelen
    - godox
    - wsl
    - wrapcheck
    - gomnd
    - gochecknoglobals
    - exhaustive
    - testpackage
    - ireturn
    - godot
    - mnd
    - nonamedreturns
    - funlen
    - gci
    - nlreturn
    - inamedparam
    - lll
    - paralleltest
    - gocognit
    - goconst
    - cyclop
    - dupword
    - whitespace
    - nolintlint
    - nestif
    - forcetypeassert
    - interfacebloat
    - revive
    - gocyclo
    - errname
    - gosmopolitan
    - maintidx

    # Todo: re-add
    - err113
    - errorlint
  fix: true
