// Code generated by goyacc expressions.y. DO NOT EDIT.

//line expressions.y:1

package expressions

import (
	"fmt"
	__yyfmt__ "fmt"

	"github.com/osteele/liquid/values"
) //line expressions.y:3

func init() {
	// This allows adding and removing references to fmt in the rules below,
	// without having to comment and un-comment the import statement above.
	_ = ""
}

//line expressions.y:15
type yySymType struct {
	yys           int
	name          string
	val           any
	f             func(Context) values.Value
	s             string
	ss            []string
	exprs         []Expression
	cycle         Cycle
	cyclefn       func(string) Cycle
	loop          Loop
	loopmods      loopModifiers
	filter_params []valueFn
}

const LITERAL = 57346
const IDENTIFIER = 57347
const KEYWORD = 57348
const PROPERTY = 57349
const ASSIGN = 57350
const CYCLE = 57351
const LOOP = 57352
const WHEN = 57353
const EQ = 57354
const NEQ = 57355
const GE = 57356
const LE = 57357
const IN = 57358
const AND = 57359
const OR = 57360
const NOT = 57361
const CONTAINS = 57362
const DOTDOT = 57363
const EMPTY = 57364
const BLANK = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LITERAL",
	"IDENTIFIER",
	"KEYWORD",
	"PROPERTY",
	"ASSIGN",
	"CYCLE",
	"LOOP",
	"WHEN",
	"EQ",
	"NEQ",
	"GE",
	"LE",
	"IN",
	"AND",
	"OR",
	"NOT",
	"CONTAINS",
	"DOTDOT",
	"EMPTY",
	"BLANK",
	"'.'",
	"'|'",
	"'<'",
	"'>'",
	"';'",
	"'='",
	"':'",
	"','",
	"'['",
	"']'",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 170

var yyAct = [...]int8{
	10, 57, 52, 23, 2, 9, 92, 28, 18, 19,
	51, 53, 53, 29, 11, 12, 41, 42, 56, 18,
	19, 43, 54, 44, 45, 49, 73, 47, 31, 8,
	86, 30, 13, 14, 63, 64, 65, 66, 67, 68,
	69, 70, 15, 55, 16, 32, 48, 31, 62, 46,
	26, 74, 21, 33, 84, 75, 78, 76, 24, 79,
	80, 77, 82, 1, 32, 89, 31, 18, 19, 25,
	11, 12, 33, 85, 3, 4, 5, 6, 87, 88,
	20, 90, 91, 32, 93, 8, 95, 96, 13, 14,
	50, 33, 22, 97, 94, 27, 31, 99, 15, 100,
	16, 34, 35, 38, 39, 11, 12, 98, 81, 40,
	72, 7, 31, 32, 0, 37, 36, 34, 35, 38,
	39, 33, 0, 13, 14, 40, 11, 12, 83, 32,
	0, 37, 36, 15, 0, 16, 31, 33, 31, 11,
	12, 18, 19, 0, 13, 14, 0, 59, 60, 61,
	0, 0, 17, 32, 15, 32, 16, 13, 14, 0,
	58, 33, 0, 33, 71, 0, 0, 15, 0, 16,
}

var yyPact = [...]int16{
	66, -1000, 124, 47, 54, 45, 135, -1000, 10, 6,
	105, -1000, -1000, -1000, -1000, 135, 10, -1000, 10, 10,
	20, 39, -3, -20, -1000, -6, 27, -10, 129, -1000,
	143, -1000, 43, 135, 135, 135, 135, 135, 135, 135,
	135, 131, 89, -9, 50, 50, 10, -1000, -1000, -1000,
	-1000, 54, -1000, 54, -1000, 135, -1000, -1000, 135, 135,
	-1000, 122, -1000, 21, 40, 40, 40, 40, 40, 40,
	40, -1000, 135, -1000, 2, -19, -19, 6, 40, 129,
	129, -25, 40, 135, -1000, 59, -1000, -1000, -1000, 81,
	-1000, -1000, 101, 40, -1000, -1000, 135, 40, 135, 40,
	40,
}

var yyPgo = [...]int8{
	0, 0, 111, 5, 4, 108, 95, 1, 92, 90,
	2, 80, 69, 65, 3, 63,
}

var yyR1 = [...]int8{
	0, 15, 15, 15, 15, 15, 11, 11, 11, 8,
	9, 9, 10, 10, 6, 7, 7, 7, 14, 12,
	13, 13, 13, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 3, 3, 5, 5, 5, 5,
	2, 2, 2, 2, 2, 2, 2, 2, 4, 4,
	4, 4,
}

var yyR2 = [...]int8{
	0, 2, 5, 3, 3, 3, 1, 2, 2, 2,
	3, 1, 0, 3, 2, 0, 3, 3, 1, 4,
	0, 2, 3, 1, 1, 1, 1, 2, 3, 4,
	3, 5, 3, 1, 3, 4, 1, 2, 3, 4,
	1, 3, 3, 3, 3, 3, 3, 3, 1, 2,
	3, 3,
}

var yyChk = [...]int16{
	-1000, -15, -4, 8, 9, 10, 11, -2, 19, -3,
	-1, 4, 5, 22, 23, 32, 34, 28, 17, 18,
	-11, 5, -8, -14, 4, -12, 5, -6, -1, -4,
	25, 7, 24, 32, 12, 13, 27, 26, 14, 15,
	20, -1, -1, -4, -4, -4, 29, 7, 7, 28,
	-9, 30, -10, 31, 28, 16, 28, -7, 31, 18,
	5, 6, 5, -1, -1, -1, -1, -1, -1, -1,
	-1, 33, 21, 35, -4, -14, -14, -3, -1, -1,
	-1, -5, -1, 6, 33, -1, 28, -10, -10, -13,
	-7, -7, 31, -1, 35, 5, 6, -1, 6, -1,
	-1,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 0, 0, 0, 48, 0, 40,
	33, 23, 24, 25, 26, 0, 0, 1, 0, 0,
	0, 6, 0, 12, 18, 0, 0, 0, 15, 49,
	0, 27, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 33, 0, 50, 51, 0, 8, 7, 3,
	9, 0, 11, 0, 4, 0, 5, 14, 0, 0,
	34, 0, 28, 0, 41, 42, 43, 44, 45, 46,
	47, 30, 0, 32, 0, 12, 12, 20, 33, 15,
	15, 35, 36, 0, 29, 0, 2, 10, 13, 19,
	16, 17, 0, 37, 31, 21, 0, 38, 0, 22,
	39,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	34, 35, 3, 3, 31, 3, 24, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 30, 28,
	26, 29, 27, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 32, 3, 33, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 25,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:48
		{
			yylex.(*lexer).val = yyDollar[1].f
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expressions.y:49
		{
			path := yyDollar[2].ss
			var variable string
			if len(path) == 1 {
				variable = path[0]
			}
			yylex.(*lexer).Assignment = Assignment{Variable: variable, Path: path, ValueFn: &expression{evaluator: yyDollar[4].f}}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:57
		{
			yylex.(*lexer).Cycle = yyDollar[2].cycle
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:58
		{
			yylex.(*lexer).Loop = yyDollar[2].loop
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:59
		{
			yylex.(*lexer).When = When{yyDollar[2].exprs}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:63
		{
			yyVAL.ss = []string{yyDollar[1].name}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:64
		{
			yyVAL.ss = []string{yyDollar[1].name, yyDollar[2].name}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:65
		{
			yyVAL.ss = append(yyDollar[1].ss, yyDollar[2].name)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:68
		{
			yyVAL.cycle = yyDollar[2].cyclefn(yyDollar[1].s)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:71
		{
			h, t := yyDollar[2].s, yyDollar[3].ss
			yyVAL.cyclefn = func(g string) Cycle { return Cycle{g, append([]string{h}, t...)} }
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:75
		{
			vals := yyDollar[1].ss
			yyVAL.cyclefn = func(h string) Cycle { return Cycle{Values: append([]string{h}, vals...)} }
		}
	case 12:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:82
		{
			yyVAL.ss = []string{}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:83
		{
			yyVAL.ss = append([]string{yyDollar[2].s}, yyDollar[3].ss...)
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:86
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[1].f}}, yyDollar[2].exprs...)
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:88
		{
			yyVAL.exprs = []Expression{}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:89
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[2].f}}, yyDollar[3].exprs...)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:90
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[2].f}}, yyDollar[3].exprs...)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:93
		{
			s, ok := yyDollar[1].val.(string)
			if !ok {
				panic(SyntaxError(fmt.Sprintf("expected a string for %q", yyDollar[1].val)))
			}
			yyVAL.s = s
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:101
		{
			name, expr, mods := yyDollar[1].name, yyDollar[3].f, yyDollar[4].loopmods
			yyVAL.loop = Loop{mods, name, &expression{evaluator: expr}}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:107
		{
			yyVAL.loopmods = loopModifiers{}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:108
		{
			switch yyDollar[2].name {
			case "reversed":
				yyDollar[1].loopmods.Reversed = true
			default:
				panic(SyntaxError(fmt.Sprintf("undefined loop modifier %q", yyDollar[2].name)))
			}
			yyVAL.loopmods = yyDollar[1].loopmods
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:117
		{
			switch yyDollar[2].name {
			case "cols":
				yyDollar[1].loopmods.Cols = &expression{evaluator: yyDollar[3].f}
			case "limit":
				yyDollar[1].loopmods.Limit = &expression{evaluator: yyDollar[3].f}
			case "offset":
				yyDollar[1].loopmods.Offset = &expression{evaluator: yyDollar[3].f}
			default:
				panic(SyntaxError(fmt.Sprintf("undefined loop modifier %q", yyDollar[2].name)))
			}
			yyVAL.loopmods = yyDollar[1].loopmods
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:133
		{
			val := yyDollar[1].val
			yyVAL.f = func(Context) values.Value { return values.ValueOf(val) }
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:134
		{
			name := yyDollar[1].name
			yyVAL.f = func(ctx Context) values.Value { return values.ValueOf(ctx.Get(name)) }
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:135
		{
			yyVAL.f = func(_ Context) values.Value { return values.EmptyDrop }
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:136
		{
			yyVAL.f = func(_ Context) values.Value { return values.BlankDrop }
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:137
		{
			yyVAL.f = makeObjectPropertyExpr(yyDollar[1].f, yyDollar[2].name)
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:138
		{
			yyVAL.f = makeObjectPropertyExpr(yyDollar[1].f, yyDollar[3].name)
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:139
		{
			yyVAL.f = makeIndexExpr(yyDollar[1].f, yyDollar[3].f)
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:140
		{
			yyVAL.f = makeVariableIndirectionExpr(yyDollar[2].f)
		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expressions.y:141
		{
			yyVAL.f = makeRangeExpr(yyDollar[2].f, yyDollar[4].f)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:142
		{
			yyVAL.f = yyDollar[2].f
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:147
		{
			yyVAL.f = makeFilter(yyDollar[1].f, yyDollar[3].name, nil)
		}
	case 35:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:148
		{
			yyVAL.f = makeFilter(yyDollar[1].f, yyDollar[3].name, yyDollar[4].filter_params)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:152
		{
			yyVAL.filter_params = []valueFn{yyDollar[1].f}
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:153
		{
			yyVAL.filter_params = []valueFn{makeNamedArgFn(yyDollar[1].name, yyDollar[2].f)}
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:155
		{
			yyVAL.filter_params = append(yyDollar[1].filter_params, yyDollar[3].f)
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:157
		{
			yyVAL.filter_params = append(yyDollar[1].filter_params, makeNamedArgFn(yyDollar[3].name, yyDollar[4].f))
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:161
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := a.Equal(b)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook("==", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:168
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := !a.Equal(b)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook("!=", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:175
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := b.Less(a)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook(">", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:182
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := a.Less(b)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook("<", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:189
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := b.Less(a) || a.Equal(b)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook(">=", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:196
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				result := a.Less(b) || a.Equal(b)
				if c, ok := ctx.(*context); ok {
					c.callComparisonHook("<=", a, b, result)
				}
				return values.ValueOf(result)
			}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:203
		{
			yyVAL.f = makeContainsExpr(yyDollar[1].f, yyDollar[3].f)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:208
		{
			fa := yyDollar[2].f
			yyVAL.f = func(ctx Context) values.Value {
				return values.ValueOf(!fa(ctx).Test())
			}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:214
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				if c, ok := ctx.(*context); ok {
					c.callGroupBeginHook()
				}
				a := fa(ctx)
				b := fb(ctx)
				result := a.Test() && b.Test()
				if c, ok := ctx.(*context); ok {
					c.callGroupEndHook("and", result)
				}
				return values.ValueOf(result)
			}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:220
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				if c, ok := ctx.(*context); ok {
					c.callGroupBeginHook()
				}
				a := fa(ctx)
				b := fb(ctx)
				result := a.Test() || b.Test()
				if c, ok := ctx.(*context); ok {
					c.callGroupEndHook("or", result)
				}
				return values.ValueOf(result)
			}
		}
	}
	goto yystack /* stack new state and value */
}
