// Code generated by goyacc expressions.y. DO NOT EDIT.

//line expressions.y:1

package expressions

import __yyfmt__ "fmt"

//line expressions.y:3
import (
	"fmt"
	"github.com/osteele/liquid/values"
)

func init() {
	// This allows adding and removing references to fmt in the rules below,
	// without having to comment and un-comment the import statement above.
	_ = ""
}

//line expressions.y:15
type yySymType struct {
	yys           int
	name          string
	val           any
	f             func(Context) values.Value
	s             string
	ss            []string
	exprs         []Expression
	cycle         Cycle
	cyclefn       func(string) Cycle
	loop          Loop
	loopmods      loopModifiers
	filter_params []valueFn
}

const LITERAL = 57346
const IDENTIFIER = 57347
const KEYWORD = 57348
const PROPERTY = 57349
const ASSIGN = 57350
const CYCLE = 57351
const LOOP = 57352
const WHEN = 57353
const EQ = 57354
const NEQ = 57355
const GE = 57356
const LE = 57357
const IN = 57358
const AND = 57359
const OR = 57360
const NOT = 57361
const CONTAINS = 57362
const DOTDOT = 57363
const EMPTY = 57364
const BLANK = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LITERAL",
	"IDENTIFIER",
	"KEYWORD",
	"PROPERTY",
	"ASSIGN",
	"CYCLE",
	"LOOP",
	"WHEN",
	"EQ",
	"NEQ",
	"GE",
	"LE",
	"IN",
	"AND",
	"OR",
	"NOT",
	"CONTAINS",
	"DOTDOT",
	"EMPTY",
	"BLANK",
	"'.'",
	"'|'",
	"'<'",
	"'>'",
	"';'",
	"'='",
	"':'",
	"','",
	"'['",
	"']'",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 136

var yyAct = [...]int8{
	10, 54, 49, 22, 2, 9, 30, 27, 48, 50,
	11, 12, 91, 28, 86, 50, 39, 56, 53, 44,
	40, 51, 41, 42, 46, 11, 12, 29, 13, 14,
	55, 31, 59, 60, 61, 62, 63, 64, 65, 66,
	15, 43, 52, 13, 14, 11, 12, 45, 69, 17,
	18, 25, 70, 73, 71, 15, 74, 75, 72, 77,
	8, 30, 20, 13, 14, 11, 12, 68, 79, 3,
	4, 5, 6, 81, 82, 15, 84, 85, 30, 23,
	8, 17, 18, 13, 14, 1, 31, 90, 83, 87,
	92, 30, 93, 30, 24, 15, 32, 33, 36, 37,
	19, 30, 47, 31, 38, 67, 32, 33, 36, 37,
	35, 34, 17, 18, 38, 21, 31, 26, 31, 78,
	35, 34, 76, 80, 17, 18, 31, 88, 89, 57,
	58, 7, 0, 0, 0, 16,
}

var yyPact = [...]int16{
	61, -1000, 107, 57, 75, 46, 21, -1000, 41, 2,
	94, -1000, -1000, -1000, -1000, 41, -1000, 41, 41, 12,
	40, -4, -22, -1000, -7, 26, -10, -1, -1000, 124,
	-1000, 21, 21, 21, 21, 21, 21, 21, 21, 84,
	32, 64, 64, 41, -1000, -1000, -1000, -1000, 75, -1000,
	75, -1000, 21, -1000, -1000, 21, 21, -1000, 21, 86,
	71, 71, 71, 71, 71, 71, 71, 21, -1000, 95,
	-16, -16, 2, 71, -1, -1, -17, 71, -1000, 54,
	-1000, -1000, -1000, 122, -1000, -1000, 6, -1000, -1000, 21,
	71, 21, 71, 71,
}

var yyPgo = [...]uint8{
	0, 0, 131, 5, 4, 122, 117, 1, 115, 102,
	2, 100, 94, 88, 3, 85,
}

var yyR1 = [...]int8{
	0, 15, 15, 15, 15, 15, 11, 11, 11, 8,
	9, 9, 10, 10, 6, 7, 7, 7, 14, 12,
	13, 13, 13, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 3, 3, 5, 5, 5, 2, 2, 2,
	2, 2, 2, 2, 2, 4, 4, 4, 4,
}

var yyR2 = [...]int8{
	0, 2, 5, 3, 3, 3, 1, 2, 2, 2,
	3, 1, 0, 3, 2, 0, 3, 3, 1, 4,
	0, 2, 3, 1, 1, 1, 1, 2, 4, 5,
	3, 1, 3, 4, 1, 3, 4, 1, 3, 3,
	3, 3, 3, 3, 3, 1, 2, 3, 3,
}

var yyChk = [...]int16{
	-1000, -15, -4, 8, 9, 10, 11, -2, 19, -3,
	-1, 4, 5, 22, 23, 34, 28, 17, 18, -11,
	5, -8, -14, 4, -12, 5, -6, -1, -4, 25,
	7, 32, 12, 13, 27, 26, 14, 15, 20, -1,
	-4, -4, -4, 29, 7, 7, 28, -9, 30, -10,
	31, 28, 16, 28, -7, 31, 18, 5, 6, -1,
	-1, -1, -1, -1, -1, -1, -1, 21, 35, -4,
	-14, -14, -3, -1, -1, -1, -5, -1, 33, -1,
	28, -10, -10, -13, -7, -7, 31, 35, 5, 6,
	-1, 6, -1, -1,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 0, 0, 0, 45, 0, 37,
	31, 23, 24, 25, 26, 0, 1, 0, 0, 0,
	6, 0, 12, 18, 0, 0, 0, 15, 46, 0,
	27, 0, 0, 0, 0, 0, 0, 0, 0, 31,
	0, 47, 48, 0, 8, 7, 3, 9, 0, 11,
	0, 4, 0, 5, 14, 0, 0, 32, 0, 0,
	38, 39, 40, 41, 42, 43, 44, 0, 30, 0,
	12, 12, 20, 31, 15, 15, 33, 34, 28, 0,
	2, 10, 13, 19, 16, 17, 0, 29, 21, 0,
	35, 0, 22, 36,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	34, 35, 3, 3, 31, 3, 24, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 30, 28,
	26, 29, 27, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 32, 3, 33, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 25,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:48
		{
			yylex.(*lexer).val = yyDollar[1].f
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expressions.y:49
		{
			path := yyDollar[2].ss
			var variable string
			if len(path) == 1 {
				variable = path[0]
			}
			yylex.(*lexer).Assignment = Assignment{Variable: variable, Path: path, ValueFn: &expression{evaluator: yyDollar[4].f}}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:57
		{
			yylex.(*lexer).Cycle = yyDollar[2].cycle
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:58
		{
			yylex.(*lexer).Loop = yyDollar[2].loop
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:59
		{
			yylex.(*lexer).When = When{yyDollar[2].exprs}
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:63
		{
			yyVAL.ss = []string{yyDollar[1].name}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:64
		{
			yyVAL.ss = []string{yyDollar[1].name, yyDollar[2].name}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:65
		{
			yyVAL.ss = append(yyDollar[1].ss, yyDollar[2].name)
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:68
		{
			yyVAL.cycle = yyDollar[2].cyclefn(yyDollar[1].s)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:71
		{
			h, t := yyDollar[2].s, yyDollar[3].ss
			yyVAL.cyclefn = func(g string) Cycle { return Cycle{g, append([]string{h}, t...)} }
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:75
		{
			vals := yyDollar[1].ss
			yyVAL.cyclefn = func(h string) Cycle { return Cycle{Values: append([]string{h}, vals...)} }
		}
	case 12:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:82
		{
			yyVAL.ss = []string{}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:83
		{
			yyVAL.ss = append([]string{yyDollar[2].s}, yyDollar[3].ss...)
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:86
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[1].f}}, yyDollar[2].exprs...)
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:88
		{
			yyVAL.exprs = []Expression{}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:89
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[2].f}}, yyDollar[3].exprs...)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:90
		{
			yyVAL.exprs = append([]Expression{&expression{evaluator: yyDollar[2].f}}, yyDollar[3].exprs...)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:93
		{
			s, ok := yyDollar[1].val.(string)
			if !ok {
				panic(SyntaxError(fmt.Sprintf("expected a string for %q", yyDollar[1].val)))
			}
			yyVAL.s = s
		}
	case 19:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:101
		{
			name, expr, mods := yyDollar[1].name, yyDollar[3].f, yyDollar[4].loopmods
			yyVAL.loop = Loop{mods, name, &expression{evaluator: expr}}
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line expressions.y:107
		{
			yyVAL.loopmods = loopModifiers{}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:108
		{
			switch yyDollar[2].name {
			case "reversed":
				yyDollar[1].loopmods.Reversed = true
			default:
				panic(SyntaxError(fmt.Sprintf("undefined loop modifier %q", yyDollar[2].name)))
			}
			yyVAL.loopmods = yyDollar[1].loopmods
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:117
		{
			switch yyDollar[2].name {
			case "cols":
				yyDollar[1].loopmods.Cols = &expression{evaluator: yyDollar[3].f}
			case "limit":
				yyDollar[1].loopmods.Limit = &expression{evaluator: yyDollar[3].f}
			case "offset":
				yyDollar[1].loopmods.Offset = &expression{evaluator: yyDollar[3].f}
			default:
				panic(SyntaxError(fmt.Sprintf("undefined loop modifier %q", yyDollar[2].name)))
			}
			yyVAL.loopmods = yyDollar[1].loopmods
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:133
		{
			val := yyDollar[1].val
			yyVAL.f = func(Context) values.Value { return values.ValueOf(val) }
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:134
		{
			name := yyDollar[1].name
			yyVAL.f = func(ctx Context) values.Value { return values.ValueOf(ctx.Get(name)) }
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:135
		{
			yyVAL.f = func(_ Context) values.Value { return values.EmptyDrop }
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:136
		{
			yyVAL.f = func(_ Context) values.Value { return values.BlankDrop }
		}
	case 27:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:137
		{
			yyVAL.f = makeObjectPropertyExpr(yyDollar[1].f, yyDollar[2].name)
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:138
		{
			yyVAL.f = makeIndexExpr(yyDollar[1].f, yyDollar[3].f)
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line expressions.y:139
		{
			yyVAL.f = makeRangeExpr(yyDollar[2].f, yyDollar[4].f)
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:140
		{
			yyVAL.f = yyDollar[2].f
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:145
		{
			yyVAL.f = makeFilter(yyDollar[1].f, yyDollar[3].name, nil)
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:146
		{
			yyVAL.f = makeFilter(yyDollar[1].f, yyDollar[3].name, yyDollar[4].filter_params)
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line expressions.y:150
		{
			yyVAL.filter_params = []valueFn{yyDollar[1].f}
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:152
		{
			yyVAL.filter_params = append(yyDollar[1].filter_params, yyDollar[3].f)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line expressions.y:154
		{
			yyVAL.filter_params = append(yyDollar[1].filter_params, makeNamedArgFn(yyDollar[3].name, yyDollar[4].f))
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:158
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(a.Equal(b))
			}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:165
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(!a.Equal(b))
			}
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:172
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(b.Less(a))
			}
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:179
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(a.Less(b))
			}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:186
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(b.Less(a) || a.Equal(b))
			}
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:193
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				a, b := fa(ctx), fb(ctx)
				return values.ValueOf(a.Less(b) || a.Equal(b))
			}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:200
		{
			yyVAL.f = makeContainsExpr(yyDollar[1].f, yyDollar[3].f)
		}
	case 46:
		yyDollar = yyS[yypt-2 : yypt+1]
//line expressions.y:205
		{
			fa := yyDollar[2].f
			yyVAL.f = func(ctx Context) values.Value {
				return values.ValueOf(!fa(ctx).Test())
			}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:211
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				return values.ValueOf(fa(ctx).Test() && fb(ctx).Test())
			}
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line expressions.y:217
		{
			fa, fb := yyDollar[1].f, yyDollar[3].f
			yyVAL.f = func(ctx Context) values.Value {
				return values.ValueOf(fa(ctx).Test() || fb(ctx).Test())
			}
		}
	}
	goto yystack /* stack new state and value */
}
